### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by csozo** [richrace/highlight-line#39] opened 2015-01-20 22:56 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:55:11)
HighlightLineView.module.exports.HighlightLineView.initialize (/home/csozo/.atom/packages/highlight-line/lib/highlight-line-view.coffee:18:9)
```

**Comment by stramel** [comment] 2015-01-23 14:40
duplicate of #38. Please close.

**Closed** 2015-02-23 09:12 UTC
