### ISSUE TITLE
Uncaught Error: No line exists for row 13. Last screen row: 12

### ISSUE THREAD

**Issue by valtido** [richrace/highlight-line#63] opened 2015-03-03 12:14 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [highlight-line](https://github.com/richrace/highlight-line) package, v0.10.1

### Stack Trace

Uncaught Error: No line exists for row 13. Last screen row: 12

```
At C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\history.js:124

Error: No line exists for row 13. Last screen row: 12
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor-presenter.js:296:17)
  at TextEditorPresenter.module.exports.TextEditorPresenter.didDestroyDecoration (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor-presenter.js:1070:16)
  at C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor-presenter.js:1023:24
  at Emitter.module.exports.Emitter.emit (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Decoration.module.exports.Decoration.destroy (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\decoration.js:59:20)
  at C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\decoration.js:46:24
  at Emitter.module.exports.Emitter.emit (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Marker.module.exports.Marker.destroyed (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\marker.js:264:20)
  at C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\marker.js:51:24
  at Emitter.module.exports.Emitter.emit (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\marker.js:318:20)
  at Marker.module.exports.Marker.destroy (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\marker.js:62:25)
  at HighlightLineView.module.exports.HighlightLineView.resetBackground (C:\Users\vcaushi\Dropbox\.atom\packages\highlight-line\lib\highlight-line-view.coffee:46:18)
  at HighlightLineView.module.exports.HighlightLineView.updateSelectedLine (C:\Users\vcaushi\Dropbox\.atom\packages\highlight-line\lib\highlight-line-view.coffee:41:6)
  at C:\Users\vcaushi\Dropbox\.atom\packages\highlight-line\lib\highlight-line-view.coffee:1:1
  at Emitter.module.exports.Emitter.emit (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.selectionRangeChanged (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor.js:2230:27)
  at Selection.module.exports.Selection.screenRangeChanged (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\selection.js:884:26)
  at C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\selection.js:45:24
  at Emitter.module.exports.Emitter.emit (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Marker.module.exports.Marker.resumeChangeEvents (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\marker.js:319:38)
  at DisplayBuffer.module.exports.DisplayBuffer.resumeMarkerChangeEvents (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\display-buffer.js:1388:16)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\display-buffer.js:319:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkersUpdated (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\display-buffer.js:1586:21)
  at C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:599:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:507:12)
  at TextBuffer.module.exports.TextBuffer.delete (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:604:19)
  at TextBuffer.module.exports.TextBuffer.deleteRows (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:636:28)
  at Selection.module.exports.Selection.deleteLine (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\selection.js:572:37)
  at C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor.js:1179:26
  at C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor.js:840:27
  at History.module.exports.History.transact (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor.js:1209:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor.js:833:19)
  at TextEditor.module.exports.TextEditor.deleteLine (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor.js:1178:19)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:delete-line (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor-element.js:443:19)
  at C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor-element.js:299:34
  at History.module.exports.History.transact (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor.js:1209:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor-element.js:298:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\vcaushi\AppData\Local\atom\app-0.184.0\resources\app\src\window-event-handler.js:182:20)

```

### Commands

```
     -3:00.9 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -2:58.6 core:delete (atom-text-editor.editor)
     -2:58.3 core:save (atom-text-editor.editor)
     -2:40.2 core:backspace (atom-text-editor.editor)
     -2:39.6 core:save (atom-text-editor.editor)
     -2:36.3 core:backspace (atom-text-editor.editor)
     -2:36.1 core:save (atom-text-editor.editor)
     -2:31.9 core:delete (atom-text-editor.editor)
  5x -2:31.4 core:save (atom-text-editor.editor)
  2x -1:12.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
  3x -1:01.2 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:39.4 pane:split-down (atom-text-editor.editor.is-focused)
     -0:35.3 editor:move-line-up (atom-text-editor.editor)
     -0:29.3 core:close (atom-pane.pane)
     -0:24.7 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:15.6 editor:delete-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "live-archive",
      "atom-compile-coffee",
      "atom-terminal",
      "background-tips",
      "welcome",
      "file-icons",
      "coffee-trace",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "git-blame",
      "dev-live-reload",
      "sublime-tabs",
      "autocomplete-paths",
      "github-issues",
      "snippets",
      "enhanced-package-list",
      "emmet",
      "linter-jscs",
      "autohide-tree-view",
      "git-projects",
      "terminal-panel",
      "recent-projects",
      "project-colorize"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "C:\\Users\\vcaushi\\dev",
    "destroyEmptyPanes": false
  },
  "highlight-line": {
    "underline": "dotted"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.11.0
atom-jasmine, v0.5.0
atom-runner, v2.3.0
atom-terminal-panel, v4.2.1
auto-reveal-in-sidebar, v0.4.0
autocomplete-plus, v2.3.0
change-case, v0.5.1
coffee-eval, v0.8.0
editor-stats, v0.17.0
highlight-line, v0.10.1
highlight-selected, v0.9.1
jsonlint, v1.0.1
language-jade, v0.3.0
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-csslint, v0.0.11
linter-jshint, v0.1.0
max-tabs, v0.3.0
minimap, v4.4.0
open-last-project, v0.3.4
project-manager, v1.15.5
project-switcher, v0.1.0
Stylus, v0.5.3
Sublime-Style-Column-Selection, v1.2.3
test-status, v0.27.1
travis-ci-status, v0.11.2
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by sdepold** [comment] 2015-03-03 14:17
I have the same problem. 

Some information about my system:

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoflow",
      "background-tips",
      "bookmarks",
      "dev-live-reload",
      "link",
      "metrics",
      "open-on-github",
      "snippets",
      "spell-check",
      "welcome",
      "linter-jscs"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "highlight-line": {
    "underline": "dashed",
    "hideHighlightOnSelect": true
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.11.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.3.0
build, v0.24.0
case-switch, v0.5.0
editorconfig, v0.3.0
esformatter, v1.3.0
highlight-line, v0.10.1
highlight-selected, v0.9.1
language-erlang, v2.0.0
linter, v0.12.0
linter-jshint, v0.1.0
```

**Comment by ScreenDriver** [comment] 2015-03-05 14:44
:+1:
Same here: Mac OS X 10.10.2 + Atom 0.186.0

**Comment by richrace** [comment] 2015-03-05 15:11
Duplicate of #61

**Closed by richrace** 2015-03-05 15:11 UTC
